###########################################
# 1. GET TODOS LOS PRODUCTOS
###########################################

GET http://localhost:8000/api/productos

###

###########################################
# 2. GET PRODUCTO POR ID
###########################################

GET http://localhost:8000/api/productos/68faa2a5a2296275fb3a608f

###